---- This file can be loaded by calling `lua require('plugins')` from your init.vim
--
---- Only required if you have packer configured as `opt`
--return require('packer').startup(function(use)
--    -- Packer can manage itself
--    use({
--        'wbthomason/packer.nvim',
--        dependencies = {
--            'williamboman/mason-lspconfig.nvim',
--            'neovim/nvim-lspconfig',
--            'hrsh7th/nvim-cmp',
--        },
--        config = function()
--            require('mason').setup()
--            require('mason-lspconfig').setup({
--                ensure_installed = {
--                    'lua_ls',
--                    'gopls',
--                    'pyright',
--                    'eslint',
--                    'rust_analyzer',
--                    'emmet_language_server',
--                    'jsonls'
--                },
--            })
--            require('mason-lspconfig').setup()
--        end,
--    })
--
--    use({
--        "mikavilpas/yazi.nvim",
--        config = function()
--            require("yazi").setup({
--                dependencies = { "folke/snacks.nvim" },
--            })
--        end,
--    })
--
--    use({ "iamcco/markdown-preview.nvim", run = "cd app && npm install", setup = function() vim.g.mkdp_filetypes = { "markdown" } end, ft = { "markdown" }, })
--
--    use({ 'kepano/flexoki-neovim', as = 'flexoki' })
--
--    use {
--        'nvim-telescope/telescope.nvim', tag = '0.1.5',
--        -- or                            , branch = '0.1.x',
--        requires = { { 'nvim-lua/plenary.nvim' } }
--    }
--
--    use({
--        "folke/trouble.nvim",
--        config = function()
--            require("trouble").setup {
--                icons = false,
--                -- your configuration comes here
--                -- or leave it empty to use the default settings
--                -- refer to the configuration section below
--            }
--        end
--    })
--
--    use { "catppuccin/nvim", as = "catppuccin" }
--
--    use({
--        "lukas-reineke/indent-blankline.nvim",
--        config = function()
--            require("ibl").setup()
--        end
--    })
--
--    use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
--    use("nvim-treesitter/playground")
--    use("theprimeagen/harpoon")
--    use("mbbill/undotree")
--    use("tpope/vim-fugitive")
--    use("nvim-treesitter/nvim-treesitter-context");
--
--    use {
--        'VonHeikemen/lsp-zero.nvim',
--        branch = 'v1.x',
--        requires = {
--            -- LSP Support
--            { 'neovim/nvim-lspconfig' },
--            { 'williamboman/mason.nvim' },
--            { 'williamboman/mason-lspconfig.nvim' },
--
--            -- Autocompletion
--            { 'hrsh7th/nvim-cmp' },
--            { 'hrsh7th/cmp-buffer' },
--            { 'hrsh7th/cmp-path' },
--            { 'saadparwaiz1/cmp_luasnip' },
--            { 'hrsh7th/cmp-nvim-lsp' },
--            { 'hrsh7th/cmp-nvim-lua' },
--
--            -- Snippets
--            { 'L3MON4D3/LuaSnip' },
--            { 'rafamadriz/friendly-snippets' },
--        }
--    }
--
--    use("folke/zen-mode.nvim")
--    use("laytan/cloak.nvim")
--    use('f-person/git-blame.nvim')
--    use { 'windwp/nvim-autopairs',
--        config = function() require("nvim-autopairs").setup {} end
--    }
--
--    use {
--        'nvim-lualine/lualine.nvim',
--        requires = { 'nvim-tree/nvim-web-devicons', opt = true }
--    }
--
--    use {
--        'numToStr/Comment.nvim',
--        config = function()
--            require('Comment').setup()
--        end
--    }
--end)
