console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Path }}'
    type = 'path'
    style = 'diamond'
    background = "#61AFEF"
    foreground = "#ffffff"
    trailing_diamond = ""
    leading_diamond = ""

    [blocks.segments.properties]
      style = 'folder'

[[blocks.segments]]
  background = "#fca308"
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#f36943{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#a8216b{{ end }}",
  "{{ if gt .Ahead 0 }}#35b5ff{{ end }}",
  "{{ if gt .Behind 0 }}#f89cfa{{ end }}"
]
  foreground = "#193549"
  foreground_templates = [ "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ffffff{{ end }}" ]
  powerline_symbol = ""
  template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }} "
  style = "powerline"
  type = "git"

    [blocks.segments.properties]
    branch_template = "{{ trunc 25 .Branch }}"
    fetch_status = true

[[blocks]]
  type = "rprompt"
  overflow = "hide"

  [[blocks.segments]]
  foreground = "#ffffff"
  background = "transparent"
  template = " :{{ .Shell }}"
  style = "plain"
  type = "shell"

[[blocks]]
  type = "rprompt"
  overflow = "hide"

  [[blocks.segments]]
  foreground = "#ffffff"
  background = "transparent"
  template = " {{ .Output }}"
   #template = " {{if gt .Output 0 }} 📋{{ .Output }} {{else}} ✅ {{end}}"
  style = "plain"
  type = "command"
    [segments.properties]
    shell="zsh"
    command="_zsh_task_get_count"
 

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    background = 'transparent'
    type = 'text'
    style = 'plain'
    template = '❯'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
